In [18]:
CORPUS=['the sky is blue',
       'sky is blue and sky is beautiful',
       'the beautiful sky is so blue',
       'i love blue cheese']
new_doc=['loving this blue sky today']

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
def bow_extractor(corpus,ngram_range=(1,1)):
    vectorizer=CountVectorizer(min_df=1,ngram_range=ngram_range)
    features=vectorizer.fit_transform(corpus)
    return vectorizer,features

In [8]:
bow_vectorizer,bow_features=bow_extractor(CORPUS)
features=bow_features.todense()
print(features)

[[0 0 1 0 1 0 1 0 1]
 [1 1 1 0 2 0 2 0 0]
 [0 1 1 0 1 0 1 1 1]
 [0 0 1 1 0 1 0 0 0]]


In [9]:
new_doc_features = bow_vectorizer.transform(new_doc)
new_doc_features = new_doc_features.todense()
print(new_doc_features)

[[0 0 1 0 0 0 1 0 0]]


In [11]:
feature_names = bow_vectorizer.get_feature_names()
print(feature_names)

['and', 'beautiful', 'blue', 'cheese', 'is', 'love', 'sky', 'so', 'the']


In [13]:
import pandas as pd

def display_features(features, feature_names):
    df = pd.DataFrame(data=features,
                      columns=feature_names)
    print(df)

In [14]:
display_features(features,feature_names)

   and  beautiful  blue  cheese  is  love  sky  so  the
0    0          0     1       0   1     0    1   0    1
1    1          1     1       0   2     0    2   0    0
2    0          1     1       0   1     0    1   1    1
3    0          0     1       1   0     1    0   0    0


In [19]:
#loving is in the testing data but not in the trainingdata
display_features(new_doc_features,feature_names)

   and  beautiful  blue  cheese  is  love  sky  so  the
0    0          0     1       0   0     0    1   0    0


In [7]:
bow_features.todense()

matrix([[0, 0, 1, 0, 1, 0, 1, 0, 1],
        [1, 1, 1, 0, 2, 0, 2, 0, 0],
        [0, 1, 1, 0, 1, 0, 1, 1, 1],
        [0, 0, 1, 1, 0, 1, 0, 0, 0]], dtype=int64)

In [2]:
from sklearn.feature_extraction.text import TfidfTransformer

In [21]:
def tfidf_transformer(bow_matrix):
    transformer=TfidfTransformer(norm='l2',smooth_idf=True,use_idf=True)
    tfidf_matrix=transformer.fit_transform(bow_matrix)
    return transformer,tfidf_matrix

In [22]:
import numpy as np
tfidf_trans,tfidf_features=tfidf_transformer(bow_features)
features=np.round(tfidf_features.todense(),2)
display_features(features,feature_names)

    and  beautiful  blue  cheese    is  love   sky    so   the
0  0.00       0.00  0.40    0.00  0.49  0.00  0.49  0.00  0.60
1  0.44       0.35  0.23    0.00  0.56  0.00  0.56  0.00  0.00
2  0.00       0.43  0.29    0.00  0.35  0.00  0.35  0.55  0.43
3  0.00       0.00  0.35    0.66  0.00  0.66  0.00  0.00  0.00


In [23]:
#show tfidf features for new_doc using build tfidf transformer
nd_tfidf=tfidf_trans.transform(new_doc_features)
nd_features=np.round(nd_tfidf.todense(),2)
display_features(nd_features,feature_names)

   and  beautiful  blue  cheese   is  love   sky   so  the
0  0.0        0.0  0.63     0.0  0.0   0.0  0.77  0.0  0.0
